local grafana = import 'grafonnet/grafana.libsonnet';
local polyStat = grafana.polystat;

{
  default: polyStat.new(
    title='Panel Title'
  ),
  custom: polyStat.new(
    colors=['#299c46', 'rgba(237, 129, 40, 0.89)', '#d44a3a'],
    interval='5m',
    polystatAnimationSpeed=2500,
    polystatColumnAutoSize=true,
    polystatColumns='',
    polystatDefaultClickThrough='',
    polystatDefaultClickThroughNewTab=false,
    polystatDefaultClickThroughSanitize=false,
    polystatDisplayLimit=100,
    polystatFontAutoScale=false,
    polystatFontSize=12,
    polystatFontType='Roboto',
    polystatGlobalDecimals=0,
    polystatGlobalDisplayMode='all',
    polystatGlobalDisplayTextTriggeredEmpty='OK',
    polystatGlobalOperatorName='current',
    polystatGlobalThresholds=[
      { color: '#d44a3a', state: 2, value: 0 },
      { color: '#73BF69', state: 0, value: 1 },
    ],
    polystatGlobalUnitFormat='none',
    polystatGradientEnabled=true,
    polystatHexagonSortByDirection=1,
    polystatHexagonSortByField='name',
    polystatMaxMetrics=0,
    polystatPolygonBorderColor='#73BF69',
    polystatPolygonBorderSize=2,
    polystatPolygonGlobalFillColor='#73BF69',
    polystatRadius='',
    polystatRadiusAutoSize=true,
    polystatRowAutoSize=true,
    polystatRows='',
    polystatShape='hexagon_pointed_top',
    polystatTooltipDisplayMode='all',
    polystatTooltipDisplayTextTriggeredEmpty='OK',
    polystatTooltipFontSize=12,
    polystatTooltipFontType='Roboto',
    polystatTooltipPrimarySortDirection=2,
    polystatTooltipPrimarySortField='name',
    polystatTooltipSecondarySortDirection=2,
    polystatTooltipSecondarySortField='value',
    polystatTooltipTimestampEnabled=false,
    savedComposites=[],
    savedOverrides=[],
    timeFrom=null,
    timeShift=null,
    title='Custom Panel Title',
  ),
}
