#!/bin/sh

export GRAFANA_VERSION=${GRAFANA_VERSION?"Please specify a GRAFANA_VERSION"}

mkdir -p grafonnet/$GRAFANA_VERSION

jsonnet --tla-code "coreRegistry=import 'registry/$GRAFANA_VERSION/registry-core.json'" \
        --tla-code "composableRegistry=import 'registry/$GRAFANA_VERSION/registry-composable.json'" \
        -S gen-imports.jsonnet |
  jsonnet -J vendor \
          -J . \
          -S \
          --tla-code "imports=import '/dev/stdin'" \
          --tla-code "version='$GRAFANA_VERSION'" \
          --tla-code "render='static'" \
          gen-schemas.jsonnet > grafonnet/$GRAFANA_VERSION/grafana.libsonnet

