local grafana = import 'grafonnet/grafana.libsonnet';
local statusMap = grafana.statusMap;

{
  discrete_color_mode: statusMap.new(
    title='Discrete color mode',
    description='Panel description',
    datasource='Prometheus',
    cards_cardMinWidth=50,
    cards_cardHSpacing=20,
    cards_cardRound=10,
    cards_cardVSpacing=20,
    color_cardColor='#f2dd11',
    color_defaultColor='#002500',
    color_mode='discrete',
    color_thresholds=[
      { color: '#F2495C', tooltip: 'error', value: '0' },
      { color: '#73BF69', tooltip: 'ok', value: '1' },
    ],
    data_decimals=1,
    data_unitFormat='integer',
    nullPointMode='as empty',
    xAxis_labelFormat='%a %m/%d %Y',
    yAxis_show=true,
    yAxis_minWidth=-1,
    yAxis_maxWidth=-1,
    tooltip_show=true,
    legend_show=true,
    yAxisSort='metrics',
    highlightCards=true,
    useMax=true,
  ),

  opacity_color_mode: statusMap.new(
    title='Opacity color mode',
    description='Panel description',
    datasource='Prometheus',
    cards_cardMinWidth=50,
    cards_cardHSpacing=20,
    cards_cardRound=10,
    cards_cardVSpacing=20,
    color_cardColor='#f2dd11',
    color_defaultColor='#002500',
    color_exponent=1,
    color_mode='opacity',
    color_colorScale='sqrt',
    data_decimals=1,
    data_unitFormat='integer',
    nullPointMode='as zero',
    xAxis_labelFormat='%a %m/%d %Y',
    yAxis_show=true,
    yAxis_minWidth=-1,
    yAxis_maxWidth=-1,
    tooltip_show=true,
    legend_show=true,
    yAxisSort='a → z',
    highlightCards=true,
    useMax=true,
  ),

  spectrum_color_mode: statusMap.new(
    title='Spectrum color mode',
    description='Panel description',
    datasource='Prometheus',
    cards_cardMinWidth=50,
    cards_cardHSpacing=20,
    cards_cardRound=10,
    cards_cardVSpacing=20,
    color_mode='spectrum',
    color_colorScheme='interpolateGnYlRd',
    data_decimals=1,
    data_unitFormat='integer',
    nullPointMode='as zero',
    xAxis_labelFormat='%a %m/%d %Y',
    yAxis_show=true,
    yAxis_minWidth=-1,
    yAxis_maxWidth=-1,
    tooltip_show=true,
    legend_show=true,
    yAxisSort='a → z',
    highlightCards=true,
    useMax=true,
  ),
}
