version: '3'
services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION?err}
  e2e:
    build:
      context: .
      args:
        CYPRESS_IMAGE: cypress/base:16
    image: grafonnet-e2e
    command: npx cypress run
    depends_on:
      - grafana
    environment:
      - CYPRESS_baseUrl=http://grafana:3000
      - CYPRESS_video=false
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js
      - ../tests:/e2e/tests
